name: tournamentmanager
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  auto_size_text: ^3.0.0
  cached_network_image: 3.3.1   #ADDED_NOT_DEMANDED
  cloud_firestore: ^5.0.0
  cloud_firestore_platform_interface: ^6.1.8   #ADDED_NOT_DEMANDED
  cloud_firestore_web: ^4.0.3   #ADDED_NOT_DEMANDED
  collection: ^1.18.0
  easy_debounce: ^2.0.3
  firebase_analytics: ^11.0.0
  firebase_analytics_platform_interface: ^4.0.0
  firebase_analytics_web: ^0.5.7+8
  firebase_app_check: ^0.3.0+5
  firebase_auth: ^5.0.0
  firebase_auth_platform_interface: ^7.1.7
  firebase_auth_web: ^5.12.1
  firebase_core: ^3.2.0
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.17.1
  firebase_storage: ^12.2.0
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.0   #ADDED_NOT_DEMANDED
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  go_router: 12.1.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_android: 6.1.20    #ADDED_NOT_DEMANDED
  google_sign_in_ios: ^5.7.6   #ADDED_NOT_DEMANDED
  google_sign_in_platform_interface: 2.4.2    #ADDED_NOT_DEMANDED
  google_sign_in_web: 0.12.1    #ADDED_NOT_DEMANDED
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_path: ^0.7.2
  page_transition: ^2.1.0
  path_provider: ^2.1.2   #ADDED_NOT_DEMANDED
  path_provider_android: ^2.2.7   #ADDED_NOT_DEMANDED
  path_provider_foundation: ^2.3.2   #ADDED_NOT_DEMANDED
  path_provider_platform_interface: ^2.1.0   #ADDED_NOT_DEMANDED
  plugin_platform_interface: 2.1.8    #ADDED_NOT_DEMANDED
  provider: ^6.1.2
  rxdart: ^0.28.0
  share_plus: 7.2.1   #ADDED_NOT_DEMANDED
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.3
  shared_preferences_foundation: ^2.4.0
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sign_in_with_apple: ^6.1.0
  sign_in_with_apple_platform_interface: ^1.1.0    #ADDED_NOT_DEMANDED
  sign_in_with_apple_web: ^2.1.0   #ADDED_NOT_DEMANDED
  simple_accordion: ^0.1.5
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1    #ADDED_NOT_DEMANDED
  stream_transform: ^2.1.0
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  url_launcher_android: 6.3.0   #ADDED_NOT_DEMANDED
  url_launcher_ios: 6.2.5   #ADDED_NOT_DEMANDED
  url_launcher_platform_interface: 2.3.2    #ADDED_NOT_DEMANDED
  lottie: ^3.1.2
  responsive_sizer: ^3.3.1
  crypto: ^3.0.3
  qr_flutter: ^4.1.0
  get: ^4.6.6

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/animation/splash_animation.json
     - assets/animation/send_mail_animation.json
     - assets/animation/confirm_animation.json
     - assets/animation/loading.json
     - assets/images/profile_picture_default.png
     - assets/images/petsy_logo_paw.png
     - assets/images/logo_slideshow_1.png
     - assets/images/logo_slideshow_2.png
     - assets/images/card_back/game_ygo_adv.jpg
     - assets/images/icons/trophy.png
     - assets/images/icons/profile.png
     - assets/images/icons/empty-box.png
     - assets/images/icons/build.png
     - assets/images/icons/default_tournament.png
     - assets/images/icons/detail_tournament.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
