// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EDy6Yj3-TeBOa1R3bKkKA72NsdmnG3o',
    appId: '1:427466387534:web:924784bb173f709ef3131f',
    messagingSenderId: '427466387534',
    projectId: 'tournament-manager-ee897',
    authDomain: 'tournament-manager-ee897.firebaseapp.com',
    storageBucket: 'tournament-manager-ee897.appspot.com',
    measurementId: 'G-2W4Q6BHSSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01X5ddvVG3XBLN-Q-rQlNERcPjKb1RG4',
    appId: '1:427466387534:android:24ead6c98e95b28ef3131f',
    messagingSenderId: '427466387534',
    projectId: 'tournament-manager-ee897',
    storageBucket: 'tournament-manager-ee897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcsraGArDmbn9oRARGuWqYO93d0aY424',
    appId: '1:427466387534:ios:69be2dd6949bed15f3131f',
    messagingSenderId: '427466387534',
    projectId: 'tournament-manager-ee897',
    storageBucket: 'tournament-manager-ee897.appspot.com',
    iosBundleId: 'com.pyroanid.tournamentmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcsraGArDmbn9oRARGuWqYO93d0aY424',
    appId: '1:427466387534:ios:69be2dd6949bed15f3131f',
    messagingSenderId: '427466387534',
    projectId: 'tournament-manager-ee897',
    storageBucket: 'tournament-manager-ee897.appspot.com',
    iosBundleId: 'com.pyroanid.tournamentmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EDy6Yj3-TeBOa1R3bKkKA72NsdmnG3o',
    appId: '1:427466387534:web:9db0671c51b3d115f3131f',
    messagingSenderId: '427466387534',
    projectId: 'tournament-manager-ee897',
    authDomain: 'tournament-manager-ee897.firebaseapp.com',
    storageBucket: 'tournament-manager-ee897.appspot.com',
    measurementId: 'G-59VXGLD75T',
  );
}
