// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPoGgXCNU6u0YP6sXfwdiSyGp85mFHK9g',
    appId: '1:405435477239:web:00b76b2ab44dfc0599f7f2',
    messagingSenderId: '405435477239',
    projectId: 'petsy-fde9e',
    authDomain: 'petsy-fde9e.firebaseapp.com',
    storageBucket: 'petsy-fde9e.appspot.com',
    measurementId: 'G-NML6SQ9K1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALe2IxtQ9cC797fhl8XGBos_HwvjN7FXM',
    appId: '1:405435477239:android:9cba80087ab30b2899f7f2',
    messagingSenderId: '405435477239',
    projectId: 'petsy-fde9e',
    storageBucket: 'petsy-fde9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6ZkUFaZhV6JYslfGfIybEG0qaT5inh4',
    appId: '1:405435477239:ios:62694c142429c69499f7f2',
    messagingSenderId: '405435477239',
    projectId: 'petsy-fde9e',
    storageBucket: 'petsy-fde9e.appspot.com',
    iosBundleId: 'com.pyroanid.petsy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6ZkUFaZhV6JYslfGfIybEG0qaT5inh4',
    appId: '1:405435477239:ios:62694c142429c69499f7f2',
    messagingSenderId: '405435477239',
    projectId: 'petsy-fde9e',
    storageBucket: 'petsy-fde9e.appspot.com',
    iosBundleId: 'com.pyroanid.petsy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPoGgXCNU6u0YP6sXfwdiSyGp85mFHK9g',
    appId: '1:405435477239:web:2f7dc50d7d322ba799f7f2',
    messagingSenderId: '405435477239',
    projectId: 'petsy-fde9e',
    authDomain: 'petsy-fde9e.firebaseapp.com',
    storageBucket: 'petsy-fde9e.appspot.com',
    measurementId: 'G-CSL5938LDS',
  );

}